### ISSUE TITLE
Not generating hulls.

### ISSUE THREAD

**Issue by imransalam** [chozabu/pypolypart#2]
pol = [array([ 418.,  418.]), array([ 378.33333333,  338.33333333]), array([ 360.,  326.]), array([ 344.,  295.]), array([ 330.375,  250.375]), array([ 330.375,  250.375]), array([ 288.2,  274. ]), array([ 288.2,  274. ]), array([ 212.        ,  158.28571429]), array([ 232.66666667,  136.33333333]), array([ 232.66666667,  136.33333333]), array([ 212.        ,  158.28571429]), array([ 212.        ,  158.28571429]), array([ 212.        ,  158.28571429]), array([ 212.        ,  158.28571429]), array([ 212.        ,  158.28571429]), array([ 181.45454545,  187.81818182]), array([ 181.45454545,  187.81818182]), array([ 181.45454545,  187.81818182]), array([ 181.45454545,  187.81818182]), array([ 229.2,  264.4]), array([ 229.2,  264.4]), array([ 157.33333333,  304.33333333]), array([ 124.5 ,  325.25]), array([ 124.5 ,  325.25]), array([ 145.,  341.]), array([ 296.5 ,  391.25]), array([ 296.5 ,  391.25]), array([ 296.5 ,  391.25]), array([ 296.5 ,  391.25]), array([ 329.5,  403. ]), array([ 329.5,  403. ]), array([ 380.,  422.]), array([ 418.,  418.])]

hulls = pypolypart.polys_to_tris_and_hulls([pol])['hulls']

**Comment by chozabu** [comment]
Hey! Sorry I missed this. @imransalam do you have any more info? python version? tried with simpler input?
I'll give it a go locally

**Comment by chozabu** [comment]
Hey! Sorry I missed this. @imransalam do you have any more info? python version? tried with simpler input?
I'll give it a go locally

**Comment by chozabu** [comment]
FWIW - I've given this a go

first, transformed into input the proram seems to accept:

`pol = [( 418., 418.), ( 378.33333333, 338.33333333), ( 360., 326.), ( 344., 295.), ( 330.375, 250.375), ( 330.375, 250.375), ( 288.2, 274. ), ( 288.2, 274. ), ( 212. , 158.28571429), ( 232.66666667, 136.33333333), ( 232.66666667, 136.33333333), ( 212. , 158.28571429), ( 212. , 158.28571429), ( 212. , 158.28571429), ( 212. , 158.28571429), ( 212. , 158.28571429), ( 181.45454545, 187.81818182), ( 181.45454545, 187.81818182), ( 181.45454545, 187.81818182), ( 181.45454545, 187.81818182), ( 229.2, 264.4), ( 229.2, 264.4), ( 157.33333333, 304.33333333), ( 124.5 , 325.25), ( 124.5 , 325.25), ( 145., 341.), ( 296.5 , 391.25), ( 296.5 , 391.25), ( 296.5 , 391.25), ( 296.5 , 391.25), ( 329.5, 403. ), ( 329.5, 403. ), ( 380., 422.), ( 418., 418.)]`

it runs, but generates no hulls, as you describe. I've tried drawing it, to see what the shape is:

`    screen.fill(black)
    pygame.draw.polygon(screen, (128,128,128), pol, 2)
    pygame.display.flip()`

Looks like it has an infinitely thin bit? Ill chop that out

`
pol = [( 212. , 158.28571429), ( 212. , 158.28571429), ( 212. , 158.28571429), ( 212. , 158.28571429), ( 181.45454545, 187.81818182), ( 181.45454545, 187.81818182), ( 181.45454545, 187.81818182), ( 181.45454545, 187.81818182), ( 229.2, 264.4), ( 229.2, 264.4), ( 157.33333333, 304.33333333), ( 124.5 , 325.25), ( 124.5 , 325.25), ( 145., 341.), ( 296.5 , 391.25), ( 296.5 , 391.25), ( 296.5 , 391.25), ( 296.5 , 391.25), ( 329.5, 403. ), ( 329.5, 403. ), ( 380., 422.), ( 418., 418.)]`

Still no luck! .. hang on, lets draw the direction of the poly

`
    ic = 1
    for p in pol:
        j = (int(p[0]), int(p[1]))
        ic+=1
        pygame.draw.circle(screen, (128,128,128), j, ic)`

well, lets try

`pol.reverse()`

Hooray! Hull generation :)

**Comment by chozabu** [comment]
Looking into this a bit more, I've done an update:

https://github.com/chozabu/pypolypart/blob/master/pygametest.py

It seems the data you provided also had several overlapping points, in this file is a simple function to prevent this from happening

**Comment by imransalam** [comment]
Hey, thanks @chozabu. I am now going to close this issue now.
